### ISSUE TITLE
Habilitar contribuidores

### ISSUE THREAD

**Issue by geekcom** [DanielHe4rt/php4noobs#11]
* Chamar o bot all-contributors  para fazer habilitar todos os contribuidores do projeto;
* Mostrar lista de contribuidores do projeto no README.md.

**Comment by geekcom** [comment]
@all-contributors please add @DanielHe4rt for code, maintenance, ideas, video, review

**Comment by geekcom** [comment]
@all-contributors please add @DanielHe4rt for code, maintenance, ideas, video, review

**Comment by geekcom** [comment]
@all-contributors please add @DanielHe4rt for code, ideas, review

**Comment by geekcom** [comment]
@all-contributors please add @geekcom for code, review, maintenance, ideas

**Comment by geekcom** [comment]
@all-contributors please add @arthurabreu00 for code

**Comment by geekcom** [comment]
Todos os contribuidores foram adicionados.

**Comment by geekcom** [comment]
@all-contributors please add @EHER for code

**Comment by geekcom** [comment]
@all-contributors please add @malukenho for review

**Comment by geekcom** [comment]
@all-contributors please add @airtonzanon for review

**Comment by geekcom** [comment]
@all-contributors please add @airtonzanon for code

**Comment by DanielHe4rt** [comment]
@all-contributors please add @Ryandgs for code

**Comment by DanielHe4rt** [comment]
@all-contributors please add @ribeirohenrique for code

**Comment by malukenho** [comment]
O que vocês acham de adicionar o contribuidor no local onde foi feita a contribuição? — PR, Issue.
Se continuar adicionando pessoas por essa issue, todos mencionados aqui vão receber notificação a não ser que manualmente deem um "Unsubscribe".

**Comment by geekcom** [comment]
> O que vocês acham de adicionar o contribuidor no local onde foi feita a contribuição? — PR, Issue.
> Se continuar adicionando pessoas por essa issue, todos mencionados aqui vão receber notificação a não ser que manualmente deem um "Unsubscribe".

Faz todo sentido pra mim

**Comment by geekcom** [comment]
Vou fechar aqui.
