### ISSUE TITLE
Funções de importação

### ISSUE THREAD

**Issue by DanielHe4rt** [DanielHe4rt/php4noobs#24]
Seria interessante no módulo intermediário explicar as funções **include()**, **include_once()**, **require** e **require_once**. Falando sobre importação/exportação de módulos no PHP que geralmente é bem confuso QUANDO usar essas funções.

**Comment by Th3Ang3lo** [comment]
Diferenças:

>função include():
Realiza a inclusão de um arquivo php dentro de outro arquivo, e caso o mesmo não exista, ele é enviado um warning avisando que não foi possível incluir.

> função require();
Também realiza a inclusão de outro arquivo PHP, mas a diferença é que ao invés de enviar um warning, o mesmo retorna um fatal error.

Já as funções include_once() e require_once() realizam a mesma coisa, porém caso você faça uma inclusão mais de uma vez sem querer do mesmo arquivo, o compilador ignora e continua funcionando.

**Comment by geekcom** [comment]
Acho que aqui já tá resolvido, pois agora decidimos por um guia.
