### ISSUE TITLE
Operadores bitwise

### ISSUE THREAD

**Issue by jjuhbotelho** [DanielHe4rt/php4noobs#29]
A explicação até o operador de negação está entendível para um "noob". Porém, antes dos operadores de deslocamento, sugiro explicar de forma simples como funciona o bit, a representação de um decimal em bit, junto com como transformar esses valores. Pois, da forma como está, o aluno não vai ver o porque de multiplicar/dividir por dois. Após isso, acredito que ficaria mais fácil a visualização desse deslocamento e o porque do resultado.

Exemplo:
A representação de 4 em bit é 100.
Para transformar esse bit em decimal, basta pegar a fórmula "2^n", onde 2 é a base do bit e n a posição em que o número está, iniciando da posição 0, ou seja:
0^0 = 0
0^1 = 0
0^2 = 4

**Comment by geekcom** [comment]
Oi @jjuhbotelho, obrigado pelas sugestões, a gente resolveu manter o tutorial o mais simples possível, por isso não aprofundamos nesse tema. Tentamos manter o foco em como o PHP funciona.

**Comment by jjuhbotelho** [comment]
Claro, seria viável então disponibilizar um link nesse caso, então?!
