### ISSUE TITLE
Incluir o PHP do jeito certo.

### ISSUE THREAD

**Issue by samuelmattos** [DanielHe4rt/php4noobs#31]
Seria interessante incluir no repositório de alguma maneira uma referência para o portal do [phptherightway](http://br.phptherightway.com/).
Esse portal é interessante pois abordas conceitos já consolidados na comunidade PHP como as PSR's.

**Comment by geekcom** [comment]
De fato as PSRs são importantes, precisamos criar algum ponto onde possamos manter esses links importantes. Pra um novato full talvez não sejá tão importante as PSRs no momento.
