### ISSUE TITLE
Sobre o projeto

### ISSUE THREAD

**Issue by brunobandev** [DanielHe4rt/php4noobs#34]
Bom dia pessoal, espero que estejam todos bem.

Eu realmente não sabia onde postar minhas perguntas, então resolvi abrir esse *issue*.
Primeiramente eu queria parabenizar pelo projeto, e acho que essa iniciativa é muito valiosa.

A primeira coisa que eu gostaria de saber é se existe um servidor do *slack* ou *discord* que centralize os colaboradores, curiosos e estudantes de **PHP** relacionado ao php4noobs.

A segunda seria uma sugestão, eu estou lendo os materias e vejo que tem alguns termos em inglês, outros em portugues. Eu acho que por se tratar de um material destinado para novatos, sempre que um termo for colocado em inglês (o que é importantíssimo), colocar o significado ou *link* para a explicação do mesmo. Pois dessa forma o novato vai aprendendo as terminologias do mercado de trabalho meio que instintivamente.

Tenho outras colocações para contribuir, mas por enquanto é isso. 
Obrigado pela atenção.

**Comment by airtonzanon** [comment]
Opa, valeu pela dica mano. Normalmente eu faço mais revisões aqui, mas acho válida a discução sobre usar termos em inglês.

Existe um discord do He4rt Developers, https://discord.gg/5kwDQuv, só entrar lá e falar com a galera.

**Comment by geekcom** [comment]
Boa sugestão @brunobandev, a gente tenta sempre manter tudo em português br, mas podemos errar, se você ver algo errado indica que a gente arruma, ou se você quiser pode submeter uma melhoria, lá no README.md a gente ensina como fazer.
