### ISSUE TITLE
Sobre contribuição com o projeto

### ISSUE THREAD

**Issue by RogerioVM** [DanielHe4rt/php4noobs#47]
Boa noite galera!

Abri essa issue para me colocar a disposição, pois não vi outra forma de comunicar. Estou estudando PHP nos ultimos 5 meses e quero muito contribuir, interagir mais com alguma comunidade aprendendo e ajudando com projetos como este.
Sei o básico, tenho alguma coisa já desenvolvida seguindo cursos e tal, mas estou a disposição para contribuir de qualquer forma, desde tradução a qualquer outro tipo de coisa que estiver ao meu alcance.

Desde já agradeço, abraços!

**Comment by geekcom** [comment]
Valeu @RogerioVM, se você achar algum problema nos textos os códigos vai abrindo novas issues.
