### ISSUE TITLE
Adicionar links 

### ISSUE THREAD

**Issue by vduggen** [DanielHe4rt/php4noobs#49]
Opa, gostei muito do tutorial, queria agradecer pelos conteúdos, vocês são fodas! 

Vi ali na parte das funções que não tem um link no final de cada lição, para ir para uma próxima lição, teria como vocês adicionarem o link, pra ficar mais fácil a ida de uma lição para outra.

**Comment by geekcom** [comment]
Valeu pela sugestão @vduggen, já abri um PR pra resolver isso.

https://github.com/DanielHe4rt/php4noobs/pull/55

**Comment by DanielHe4rt** [comment]
PR aprovado!
