### ISSUE TITLE
Erro de exemplo no capítulo 3.5

### ISSUE THREAD

**Issue by Maju-kohler** [DanielHe4rt/php4noobs#65]
Olá bom dia! Queria agradecer por disponibilizarem esses conteúdos tão importantes para a comunidade de maneira gratuita, mandaram bem demais!
Estou aprendendo a usar o Github a pouco tempo então demorei um pouquinho para descobrir como reportar um erro pequeno que encontrei num dos capítulos, mas me achei hehe...

Então, no capítulo de Operadores Aritméticos, o exemplo de Multiplicação é igual ao de Subtração, não sei como arrumar ele e nem se eu devo, então vim reportar aqui mesmo, tirando isso não encontrei nenhum outro erro significativo ainda. 

Espero ter ajudado! Continuem arrasando!

**Comment by DanielHe4rt** [comment]
Olá Maju! Realmente, tem um leve equivoco ali no exemplo... Podemos arrumar, mas também podemos te dar essa oportunidade de fazer a primeira contribuição no nosso repositório. 

Nós também temos um repositório básico de Git para iniciantes e se quiser podemos ver como ajudar nesse quesito. Quando você quiser fazer seu primeiro pull request, só pingar aqui ou no Twitter que a gente faz isso ai! Segue o link:

https://github.com/danielhe4rt/git4noobs

**Comment by lucalves** [comment]
Aberto o PR #75, para correção :)

**Comment by lucalves** [comment]
Pessoal, podem fechar essa Issue. Solucionada no #75.
