### ISSUE TITLE
3.14 Estruturas de Controle: Loops (Erros encontratos)

### ISSUE THREAD

**Issue by kaicdteodoro** [DanielHe4rt/php4noobs#76]
Olá, estou começando a estudar PHP para ingressar em um estágio, feliz estou por acaso kkk, queria agradecer em nome da comunidade pelo repositório, pois ajuda muito quem está começando. Gostaria só de reportar dois erros de semântica que eu encontrei enquanto estudava, os dois estão no cap. 3.14, especificadamente no exemplo 2, onde se encontra essa linha de código:
echo $multiplicador . " x " . $i  . " = " ($multiplicador & $i) . PHP_EOL;
Percebe-se a falda do indicador de concatenação entre a string " = " e a variável que será impressa $multiplicador; 
Além disso, na conta efetuada ($multiplicador & $i), esperava-se o operador lógico *, que remete a multiplicação efetuada;
Desde já agradeço a compreensão, e mais uma vez, ótimo trabalho!

**Comment by matheusth** [comment]
enviado pull request com solicitação de correção. PR #79.
