### ISSUE TITLE
roadmap to noob php developers

### ISSUE THREAD

**Issue by thiagon4code** [DanielHe4rt/php4noobs#8]
Olá pessoal, tudo certo?
Gostei da iniciativa do repo, passarei a contribuir por aqui como der!

Estava pensando se poderíamos criar algo similar à [isto](https://github.com/kamranahmedse/developer-roadmap). No caso seria resumido especificamente ao PHP. 

Assim o iniciante da linguagem poderia visualizar o "caminho das pedras" de uma maneira alternativa a listagem simples. O que acham?

**Comment by geekcom** [comment]
Parece uma boa ideia @thiagon4code

**Comment by DanielHe4rt** [comment]
Eu apoio 100% a ideia de ter um Roadmap! Caso você possa criar algo do tipo pra gente, seria interesante d++

E obrigado pela contribuição de ideias!

**Comment by geekcom** [comment]
Na real mesmo, roadmap nós já temos, só não temos isso como uma imagem.
